#!/bin/bash
ssh -i /home/centos/key.pem user@0.0.0.0 show run > last
diff show_run_base last > difference.txt

if  [  -s /home/centos/difference.txt  ]
#	then echo "file is not empty"
	then ./email
else
	echo "file is empty"

fi
