#!/usr/bin/env python3
import requests
import smtplib, ssl
import os
import subprocess


port = 465  # For SSL
smtp_server = "smtp.gmail.com"
sender_email = "@gmail.com"  # Enter your address
receiver_email = "@blah.com"  # Enter receiver address
password = "" # Enter email password

message = subprocess.getoutput('cat difference.txt')

def check():

    # Sends email
    context = ssl.create_default_context()
    with smtplib.SMTP_SSL(smtp_server, port, context=context) as server:           
           server.login(sender_email, password)
           server.sendmail(sender_email, receiver_email, message)
check()
